### PR TITLE
fix: Clear functions for feeExemptKeys and customFees

### LINKED ISSUE #2281: `.clearCustomFees()`, `.clearFeeExemptKeys()` and `.clearFeeScheduleKey()` functions are not working properly in `TopicUpdateTransaction`
### Description

Upon creating a `TopicUpdateTransaction` you are not able to clear the custom fees, feeExemptKey and FeeScheduleKey.  

When you execute the transaction it executes with `SUCCESS` but the fields are not cleared and the account will be still charged with a topic fee. 
You can update the topic with new values using `.setFeeScheduleKey()`, `.setCustomFees()`, `.setFeeExemptKeys()`, but not able to clear them

According to the protobuf documentation you should be able to clear the custom fees by passing an empty list
```
     * If this field is set, but contains an empty list, all current custom fees
     * SHALL be removed.
```

Stumbled upon this issue while adding acceptance tests in mirror node for the custom topic fees according to [HIP-991](https://hips.hedera.com/hip/hip-991)

tested with com.hedera.hashgraph.sdk:2.50.0

### Steps to reproduce

1. Create a topic with custom fee and set feeScheduleKey and feeExemptKeyList
3. Update the topic with each of `.clearCustomFees()`, `.clearFeeExemptKeys()` and `.clearFeeScheduleKey()` ,  sign with FeeScheduleKey, and verify the topic again. You will notice that none of the fields is cleared

### Additional context

_No response_

### Hedera network

_No response_

### Version

2.50.0

### Operating system

None

### PR DESCRIPTION
**Pull request by naydenovn**
**Description**:
This PR focuses on solving an issue related to the clear functions of the `feeExemptKeys`, `customFees` and `feeScheduleKey` that were introduced in https://hips.hedera.com/hip/hip-991. 

The logic is updated as follows:
- If we have `null` list (that is the default value) → Do nothing (don’t send a request).
- If we have empty list → Send a request to clear the list. 
- For Non-empty list → Send a request with the provided list.
- `clearFeeScheduleKey` sets the key to empty `KeyList`.

**Related issue(s)**:

Fixes #2281

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java [hunk 1]
```diff
@@ -359,7 +359,7 @@ public TopicUpdateTransaction setFeeScheduleKey(Key feeScheduleKey) {
 
     public TopicUpdateTransaction clearFeeScheduleKey() {
         requireNotFrozen();
-        this.feeScheduleKey = null;
+        this.feeScheduleKey = new KeyList();
```
Comment (0xivanov) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java:362]: Could actually work, did not think about that.

Comment (naydenovn) [reply sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java:362]: Works as expected. Tested in latest commit

File: sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java [hunk 2]
```diff
@@ -402,6 +402,9 @@ public TopicUpdateTransaction addFeeExemptKey(Key feeExemptKey) {
         Objects.requireNonNull(feeExemptKey);
         if (feeExemptKeys != null) {
             feeExemptKeys.add(feeExemptKey);
+        } else {
```
Comment (0xivanov) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java:405]:
```java
    public TopicUpdateTransaction addFeeExemptKey(Key feeExemptKey) {
        Objects.requireNonNull(feeExemptKey);
        requireNotFrozen();
        if (feeExemptKeys == null) {
            feeExemptKeys = new ArrayList<>();
        }
        feeExemptKeys.add(feeExemptKey);
        return this;
    }

```

File: sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java [hunk 3]
```diff
@@ -446,8 +449,13 @@ public TopicUpdateTransaction clearCustomFees() {
      * @return {@code this}
      */
     public TopicUpdateTransaction addCustomFee(CustomFixedFee customFixedFee) {
-        Objects.requireNonNull(customFees);
-        customFees.add(customFixedFee);
+        Objects.requireNonNull(customFixedFee);
```
Comment (0xivanov) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java:452]:
```java
    public TopicUpdateTransaction addCustomFee(CustomFixedFee customFixedFee) {
        Objects.requireNonNull(customFixedFee);
        requireNotFrozen();
        if (customFees == null) {
            customFees = new ArrayList<>();
        }
        customFees.add(customFixedFee);
        return this;
    }

```

File: sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java [hunk 4]
```diff
@@ -422,4 +422,77 @@ private TokenId createToken(IntegrationTestEnv testEnv) throws Exception {
 
         return Objects.requireNonNull(tokenCreateResponse.getReceipt(testEnv.client).tokenId);
     }
+
+    @Test
+    @DisplayName("Can clear customFeesList, feeExemptKeysList and feeScheduleKey")
+    void canClearCustomFeesListAndFeeExemptKeysList() throws Exception {
```
Comment (0xivanov) [inline sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java:428]: Add a test where we create topic and execute update topic without setting anything aside from the `topicID` - before and after should be the same.

File: sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java [hunk 5]
```diff
@@ -422,4 +422,142 @@ private TokenId createToken(IntegrationTestEnv testEnv) throws Exception {
...
+            for (int i = 0; i < customFixedFees.size(); i++) {
+                assertThat(info.customFees.get(i).getAmount())
+                        .isEqualTo(customFixedFees.get(i).getAmount());
+                assertThat(info.customFees.get(i).getDenominatingTokenId())
+                        .isEqualTo(customFixedFees.get(i).getDenominatingTokenId());
+            }
+
+            var topicUpdate = new TopicUpdateTransaction().setTopicId(topicId).execute(testEnv.client);
+
+            topicUpdate.getReceipt(testEnv.client);
```
Comment (0xivanov) [inline sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java:554]: nit: can chain the `.execute` and `.getReceipt`

File: sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java [hunk 6]
```diff
@@ -422,4 +422,142 @@ private TokenId createToken(IntegrationTestEnv testEnv) throws Exception {
...
+            var clearFeeExemptKeysAndFeeScheduleKey = new TopicUpdateTransaction()
+                    .setTopicId(topicId)
+                    .clearFeeExemptKeys()
+                    .clearFeeScheduleKey()
+                    .clearCustomFees()
+                    .freezeWith(testEnv.client)
+                    .sign(newFeeScheduleKey)
+                    .execute(testEnv.client);
+
+            clearFeeExemptKeysAndFeeScheduleKey.getReceipt(testEnv.client);
```
Comment (0xivanov) [inline sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java:490]: nit: can chain the .execute and .getReceipt

File: sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java [hunk 7]
```diff
@@ -525,20 +529,22 @@ ConsensusUpdateTopicTransactionBody.Builder build() {
...
+        if (feeExemptKeys != null) {
             for (var feeExemptKey : feeExemptKeys) {
                 feeExemptKeyList.addKeys(feeExemptKey.toProtobufKey());
             }
             builder.setFeeExemptKeyList(feeExemptKeyList);
         }
-        if (!customFees.isEmpty()) {
-            var protoCustomFeeList = FixedCustomFeeList.newBuilder();
+
+        var protoCustomFeeList = FixedCustomFeeList.newBuilder();
```
Comment (0xivanov) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/TopicUpdateTransaction.java:540]: This line can be moved in the `if`

**Review by 0xivanov — APPROVED** [review]
LGTM
